[phases.setup]
nixPkgs = ['php', 'php81Extensions.pdo', 'php81Extensions.pdo_sqlite', 'composer', 'nodejs', 'npm']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port $PORT' 