[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_sqlite', 'php83Extensions.intl', 'php83Extensions.zip', 'php83Extensions.gd', 'php83Extensions.mbstring', 'composer', 'nodejs', 'npm']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port $PORT' 